function HdN01 = filterN01


% MATLAB Code
% Generated by MATLAB(R) 24.2 and DSP System Toolbox 24.2.
% Generated on: 11-Aug-2025 00:05:19

% Equiripple Highpass filter designed using the FIRPM function.

% All frequency values are in Hz.
Fs = 64000000;  % Sampling Frequency

Fstop = 8500000;         % Stopband Frequency
Fpass = 10000000;        % Passband Frequency
Dstop = 0.0001;          % Stopband Attenuation
Dpass = 0.057501127785;  % Passband Ripple
dens  = 20;              % Density Factor

% Calculate the order from the parameters using FIRPMORD.
[N, Fo, Ao, W] = firpmord([Fstop, Fpass]/(Fs/2), [0 1], [Dstop, Dpass]);

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, Fo, Ao, W, {dens});
HdN01 = dfilt.dffir(b);

% [EOF]
